Api de Produtos
---
    tags:
      - Produto API
    parameters:
      - name: product_id
        in: path
        type: integer
        required: true
        description: Código do produto
    responses:
      404:
        description: Produto não econtrado!
      202:
        description: Produto deletado!
        schema:
          id: produto
          properties:
            id:
              type: integer
              description: Código do produto
            category:
              type: string
              description: Categoria do produto
            name:
              type: string
              description: Nome do produto
            price:
              type: float
              default: 0